app = "chainpipe-indexer"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.indexer"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[env]
  INDEXER_PORT = "8080"
  SOLANA_RPC_URL = "https://api.devnet.solana.com"
  CHAINPIPE_USDC_MINT = "8BPRrfsXT3FZUvxW5v5ctq8Q5moZinNu7eFR4gtFPxz1"
  POLL_INTERVAL_MS = "8000"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
